---

# Tasks file for mysql-backup

- file:
    path: "{{ mysqlbackup_credentials_file }}"
    mode: 0400


- name: Load the OS specific varibles
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family }}.yml"


- include : install_debian.yml
  tags    :
    - install
    - locales
  when: ansible_os_family == "Debian"


- include : install_xtrabackup.yml
  tags    :
    -install
    - mysql-backup


- include : install_mysqldump_secure.yml
  tags    :
    - install
    - mysql-backup
